project:
  type: website
  output-dir: docs

website:
  draft-mode: gone
  google-analytics:
    tracking-id: "G-4174EVHDM6"
  title: "Home"
  favicon: vivek_cropped.JPG
  site-url: "https://vsriram24.github.io"
  description: "Vivek Sriram - Senior Health AI Scientist | Personal website and blog"

  search:
    location: navbar
    type: overlay

  navbar:
    background: "#99bb8a"
    pinned: true
    right:
      - about.qmd
      - blog.qmd
      - projects.qmd
      - teaching.qmd
      - conferences.qmd
      - publications.qmd
      - icon: rss
        href: blog.xml
        aria-label: RSS

format:
  html:
    theme:
      light: [cosmo, custom.scss]
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true

editor: visual
